services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  discord-bot:
    build:
      context: ./discord_bot
    depends_on:
      - n8n
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - N8N_API_BASE=${N8N_API_BASE}
    restart: unless-stopped

  import-agents:
    image: curlimages/curl:latest
    volumes:
      - ./agents:./agents:ro
      - ./scripts/import_agents.sh:./scripts/import_agents.sh:ro
    environment:
      - N8N_URL=http://n8n:5678
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    entrypoint: ["/bin/sh", "-c", "sh ./scripts/import_agents.sh"]
