# start n8n
# start discord bot
# sync workflows/agents into n8n

version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  discord-bot:
    build:
      context: ./discord_bot
    depends_on:
      - n8n
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - N8N_API_BASE=${N8N_API_BASE}
    restart: unless-stopped

  import-agents:
    image: curlimages/curl:latest
    depends_on:
      - n8n
    volumes:
      - ./agents:/agents:ro
      - ./import_agents.sh:/import_agents.sh:ro
    environment:
      - N8N_URL=http://n8n:5678
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
    entrypoint: ["/bin/sh", "-c", "sleep 10 && sh /import_agents.sh"]
    restart: "no"

volumes:
  n8n_data: